#ifndef RESOURCES_H
#define RESOURCES_H

#define IDM_MAIN_MENU 1024

#define ID_FILE_OPEN 1
#define ID_FILE_CLOSE 2
#define ID_FILE_EXIT 3
#define ID_TOOLS_DISASSEMBLER 4
#define ID_TOOLS_MEMORY_MAP 5
#define ID_HELP_ABOUT 6

#endif 
